scp ../manuscript/AppendixS1.pdf rocabert@puhti.csc.fi:/scratch/project_2003847/Koch_et_al_SupportingInformation/.
scp ../manuscript/DataS1.vcf.gz rocabert@puhti.csc.fi:/scratch/project_2003847/Koch_et_al_SupportingInformation/.
scp ../manuscript/DataS2.vcf.gz rocabert@puhti.csc.fi:/scratch/project_2003847/Koch_et_al_SupportingInformation/.
scp ../manuscript/DataS3.vcf.gz rocabert@puhti.csc.fi:/scratch/project_2003847/Koch_et_al_SupportingInformation/.
scp ../manuscript/DataS4.tar.gz rocabert@puhti.csc.fi:/scratch/project_2003847/Koch_et_al_SupportingInformation/.
scp ../manuscript/DataS5.vcf.gz rocabert@puhti.csc.fi:/scratch/project_2003847/Koch_et_al_SupportingInformation/.
scp ../manuscript/DataS6.tar.gz rocabert@puhti.csc.fi:/scratch/project_2003847/Koch_et_al_SupportingInformation/.
scp ../manuscript/DataS7.tar.gz rocabert@puhti.csc.fi:/scratch/project_2003847/Koch_et_al_SupportingInformation/.
scp ../manuscript/DataS8.tar.gz rocabert@puhti.csc.fi:/scratch/project_2003847/Koch_et_al_SupportingInformation/.
